/* Alvor · Spanish (Spain, "tú"). Each English text of the app → its Spanish text.
   {placeholders} must stay as they are. Plant names are in species-es.js; the alert texts in alerts.js.
   Another language: copy this file as lang-xx.js and translate the right-hand side. */
window.ALVOR_LANG = window.ALVOR_LANG || {};
window.ALVOR_LANG.es = {
/* ---- Words used all over ---- */
"Alvor":"Alvor", "@username":"@usuario",
"Cancel":"Cancelar", "Back":"Atrás", "Next":"Siguiente", "Close":"Cerrar", "Save":"Guardar", "Saved":"Guardado", "Saving…":"Guardando…",
"Delete":"Borrar", "Remove":"Quitar", "Change":"Cambiar", "Done":"Listo", "Continue":"Continuar", "Later":"Más tarde", "Yes":"Sí", "or":"o",
"Loading…":"Cargando…", "One moment…":"Un momento…", "Copied":"Copiado", "Copy this:":"Copia esto:", "You":"Tú", "Someone":"Alguien",
"More":"Más", "Add":"Añadir", "Move":"Mover", "Moved":"Movida", "All":"Todas", "new":"nuevo", "now":"ahora",
"{n} min":"{n} min", "{n} h":"{n} h", "{n} d":"{n} d", "{n} plant":"{n} planta", "{n} plants":"{n} plantas", "plant":"planta", "a plant":"una planta",
"Today":"Hoy", "today":"hoy", "days":"días", "Name":"Nombre", "Notes":"Notas", "History":"Historial", "Species":"Especie", "Genus":"Género", "genus":"género",
"Garden":"Jardín", "Your garden":"Tu jardín", "Home":"Inicio", "Locations":"Lugares", "Location":"Ubicación", "Plants":"Plantas", "Community":"Comunidad",
"Settings":"Ajustes", "Menu":"Menú", "Your account":"Tu cuenta", "More: profile, settings and account":"Más: perfil, ajustes y cuenta",
"Check your connection and try again.":"Revisa la conexión y vuelve a intentarlo.",
"Couldn't reach Alvor":"No se ha podido conectar con Alvor", "Couldn't reach Alvor. Check your connection.":"No se ha podido conectar con Alvor. Revisa la conexión.",
"Couldn't reach Alvor. Check your connection and try again.":"No se ha podido conectar con Alvor. Revisa la conexión y vuelve a intentarlo.",
"Couldn't save. Check your connection.":"No se ha podido guardar. Revisa la conexión.",

/* ---- Places and spots ---- */
"House":"Casa", "Inside the house":"Dentro de casa", "Porch":"Porche", "Covered, rain doesn't reach":"Cubierto, no le llega la lluvia",
"Outside":"Exterior", "In the open garden":"En el jardín, al aire libre", "Greenhouse":"Invernadero", "Sheltered, a few degrees warmer":"Resguardado, unos grados más cálido",
"Balcony":"Balcón", "Outside on the balcony":"Fuera, en el balcón", "Inside":"Interior", "Inside the apartment":"Dentro del piso",
"Inside all year":"Dentro todo el año", "On the balcony all year":"En el balcón todo el año", "Balcony in summer, inside in winter":"En el balcón en verano, dentro en invierno",
"Outside all year":"Fuera todo el año", "Outside in summer, inside in winter":"Fuera en verano, dentro en invierno", "Outside in summer, greenhouse in winter":"Fuera en verano, en el invernadero en invierno",
"By a window":"Junto a una ventana", "Window":"Ventana", "Inside, in good light":"Dentro, con buena luz", "Low light":"Poca luz", "Inside, away from the windows":"Dentro, lejos de las ventanas",
"Grow cabinet":"Armario de cultivo", "Under grow lights":"Bajo luces de cultivo", "Porch, partial sun":"Porche, semisombra", "Partial sun":"Semisombra",
"Some direct sun during the day":"Algo de sol directo durante el día", "Porch, shade":"Porche, sombra", "Shade":"Sombra", "Little or no direct sun":"Poco o ningún sol directo",
"Outside, sun":"Exterior, sol", "Sun":"Sol", "Sun most of the day":"Sol casi todo el día", "Outside, partial sun":"Exterior, semisombra", "Sun for part of the day":"Sol parte del día",
"Outside, shade":"Exterior, sombra", "Mostly in shade":"Casi siempre a la sombra", "Balcony, sun":"Balcón, sol", "Balcony, partial sun":"Balcón, semisombra", "Balcony, shade":"Balcón, sombra",
", in the ground":", en tierra", ", in a pot":", en maceta", "Indoors":"Interior", "Outdoors":"Exterior", "Sheltered":"Resguardado",
"Two spaces, one home":"Dos espacios, un hogar", "Three spaces, one garden":"Tres espacios, un jardín", "Wintering guests":"Invitados de invierno",
"All plants":"Todas las plantas", "Open garden":"Jardín al aire libre", "Selected plants":"Plantas elegidas",
"Where inside?":"¿Dónde, dentro?", "Where outside?":"¿Dónde, fuera?", "Which part of the balcony?":"¿Qué parte del balcón?", "In the garden":"En el jardín",
"On the porch":"En el porche", "covered, rain doesn't reach":"cubierto, no le llega la lluvia", "How is it planted?":"¿Cómo está plantada?", "Planted":"Plantada",
"In a pot":"En maceta", "In the ground":"En tierra",

/* ---- Who sees a plant ---- */
"Friends":"Amigos", "Friends see its name, species, spot and photos. Never your notes or watering.":"Tus amigos ven su nombre, especie, sitio y fotos. Nunca tus notas ni los riegos.",
"Only me (Vault)":"Solo yo (Cámara)", "Only me":"Solo yo", "Only you see it. It stays in its spot with all its alerts.":"Solo la ves tú. Sigue en su sitio con todos sus avisos.",
"Everyone":"Todos", "Anyone on Alvor can see it.":"Cualquiera en Alvor puede verla.", "Vault":"Cámara",
"In your Vault: only you see it":"En tu Cámara: solo la ves tú", "(in your Vault)":"(en tu Cámara)", "Visible to:":"Visible para:", "Visible to":"Visible para",

/* ---- Home: weather and forecast ---- */
"Next 7 days":"Próximos 7 días", "Today in your garden":"Hoy en tu jardín", "Current weather, tap to refresh":"Tiempo actual, toca para actualizar",
"H {t}":"Máx {t}", "L {t}":"Mín {t}", "Updated {time}":"Actualizado a las {time}", "Tap the weather to refresh":"Toca el tiempo para actualizar",
"Loading forecast…":"Cargando la previsión…", "No forecast yet. Tap the weather at the top to try again.":"Aún no hay previsión. Toca el tiempo arriba para volver a intentarlo.",
"{day}, {hi} to {lo}":"{day}, de {hi} a {lo}", ", warning":", aviso", "High":"Máx", "Low":"Mín", "Rain mm":"Lluvia mm",
"Down to {t}, too cold for {names}.":"Baja a {t}, demasiado frío para {names}.", "Up to {t}, too hot for {names}.":"Sube a {t}, demasiado calor para {names}.",
"Clear":"Despejado", "Partly cloudy":"Parcialmente nublado", "Cloudy":"Nublado", "Fog":"Niebla", "Rain":"Lluvia", "Snow":"Nieve", "Thunderstorm":"Tormenta",
"Tap to refresh the weather":"Toca para actualizar el tiempo", "Frost risk":"Riesgo de helada", "Cold night":"Noche fría", "Heat":"Calor",
"{n} needs water":"{n} necesita agua", "{n} need water":"{n} necesitan agua", "All calm today":"Hoy todo tranquilo", "{n} at risk tonight":"{n} en riesgo esta noche",
"Couldn't load the forecast":"No se ha podido cargar la previsión",

/* ---- Home: alerts ---- */
"Bring {n} plant inside:":"Mete {n} planta dentro:", "Bring {n} plants inside:":"Mete {n} plantas dentro:",
"Move {n} plant to the greenhouse:":"Pasa {n} planta al invernadero:", "Move {n} plants to the greenhouse:":"Pasa {n} plantas al invernadero:",
"Shelter this pot:":"Resguarda esta maceta:", "Shelter these {n} pots:":"Resguarda estas {n} macetas:",
"Protect {n} plant in the ground:":"Protege {n} planta en tierra:", "Protect {n} plants in the ground:":"Protege {n} plantas en tierra:",
"Frost alert":"Alerta de helada", "Low temperature alert":"Alerta de frío", "Low temperature watch":"Atención al frío", "Frost is coming":"Llega una helada",
"Too cold for these plants":"Demasiado frío para estas plantas", "A cold night ahead":"Se acerca una noche fría", "Heat alert":"Alerta de calor",
"Open the greenhouse":"Abre el invernadero", "A hot spell":"Ola de calor", "Wind alert":"Alerta de viento", "Strong gusts":"Rachas fuertes", "Watering":"Riego",
"{n} plant needs water":"{n} planta necesita agua", "{n} plants need water":"{n} plantas necesitan agua", "Skip these, rain is coming":"No las riegues, viene lluvia",
"Good news":"Buenas noticias", "Safe to move outside":"Ya pueden salir fuera", "Heads-up":"Atención", "Start with your plants":"Empieza por tus plantas",
"Add each plant once. Alerts and watering reminders then appear here every day.":"Añade cada planta una vez. Los avisos y recordatorios de riego aparecerán aquí cada día.",
"Add plant":"Añadir planta", "All good":"Todo bien", "Nothing to do today":"Hoy no hay nada que hacer",
"No plant needs water, and the next three days stay within what your plants can take.":"Ninguna planta necesita agua, y los próximos tres días se quedan dentro de lo que aguantan tus plantas.",
"Mark as moved":"Marcar como movidas", "Mark all watered":"Marcar todas como regadas", "See plants":"Ver plantas",
"Too cold":"Demasiado frío", "Too hot":"Demasiado calor", "Strong wind":"Viento fuerte", "Needs water":"Necesita agua", "Time to move":"Hora de moverla",
"Your house and garden":"Tu casa y tu jardín", "The porch":"El porche", "Your apartment and balcony":"Tu piso y tu balcón", "The balcony":"El balcón",
"Tap an area to look closer.":"Toca una zona para verla de cerca.", "Tap a spot to see its plants.":"Toca un sitio para ver sus plantas.", "Back to the whole garden":"Volver a todo el jardín",
"Change your own {place} photo":"Cambiar tu foto de {place}", "Add your own {place} photo":"Añadir tu propia foto de {place}", "no plants yet":"aún sin plantas",

/* ---- Plants ---- */
"Search plants":"Buscar plantas", "Show plants as":"Ver las plantas como", "List":"Lista", "Grid":"Cuadrícula", "Small tiles":"Miniaturas", "Back to locations":"Volver a lugares",
"From the alert: {n}":"Del aviso: {n}", "No plants yet":"Aún no hay plantas",
"Tap Add plant and take a photo; the app suggests the species for you.":"Toca Añadir planta y haz una foto; la app te sugiere la especie.",
"No plants match. Clear the search or pick another filter.":"Ninguna planta coincide. Borra la búsqueda o elige otro filtro.",
"never watered":"nunca regada", "rain {n}d ago":"lluvia hace {n} d", "watered {n}d ago":"regada hace {n} d", "Watered":"Regada",
"Open {name}":"Abrir {name}", "Move {name}":"Mover {name}", "Mark {name} watered":"Marcar {name} como regada",
"takes {t}":"aguanta {t}", "Low temperature warnings are off for this plant":"Los avisos de frío están desactivados para esta planta", "no low temp alerts":"sin avisos de frío",
"{n} plants watered":"{n} plantas regadas", "Deleted plant":"Planta borrada",
"Add a plant":"Añadir una planta", "Edit plant":"Editar planta", "Take a photo":"Hacer una foto", "From gallery":"De la galería",
"e.g. Big banana by the pond":"p. ej. La platanera grande del estanque", "Start typing, e.g. Musa basjoo":"Empieza a escribir, p. ej. Musa basjoo",
"Pick one from the list to fill in the genus, cold limit and watering.":"Elige una de la lista para rellenar el género, el límite de frío y el riego.", "e.g. Musa":"p. ej. Musa",
"Where it lives through the year":"Dónde vive a lo largo del año", "Where it is now":"Dónde está ahora", "Low temperature warnings for this plant":"Avisos de frío para esta planta",
"Lowest °C it takes":"Mínima que aguanta (°C)", "Water every (summer)":"Regar cada (verano)", "Water every (winter)":"Regar cada (invierno)", "Last watered":"Último riego",
"From friends":"De tus amigos", "Save plant":"Guardar planta",
"You're warned when the forecast gets close to the lowest temperature it takes.":"Recibes un aviso cuando la previsión se acerca a la mínima que aguanta.",
"No low temperature warnings for this plant. Heat, wind and watering reminders still come.":"Sin avisos de frío para esta planta. Los de calor, viento y riego siguen llegando.",
"Give the plant a name":"Ponle un nombre a la planta", "Add the lowest temperature it takes, or switch low temperature warnings off":"Añade la mínima que aguanta, o desactiva los avisos de frío",
"Couldn't save the photo":"No se ha podido guardar la foto", "Plant saved":"Planta guardada", "Delete {name}? Its history stays in the log.":"¿Borrar {name}? Su historial se queda en el registro.",
"Plant deleted":"Planta borrada", "More species from GBIF":"Más especies de GBIF", "Nothing logged yet.":"Aún no hay nada registrado.",
"Photo from {date}":"Foto del {date}", "Hidden from friends":"Oculta a tus amigos", "No photos yet. The newest photo becomes the plant's picture.":"Aún no hay fotos. La más reciente será la imagen de la planta.",
"Couldn't add that photo":"No se ha podido añadir esa foto", "Show to friends":"Mostrar a tus amigos", "Hide from friends":"Ocultar a tus amigos",
"Friends can see this photo":"Tus amigos pueden ver esta foto", "Delete this photo?":"¿Borrar esta foto?", "Photo deleted":"Foto borrada",
"Filled in for {s}.":"Datos de {s}.", "Filled in for the genus {s}.":"Datos del género {s}.", "Filled in from its genus, {s}.":"Datos de su género, {s}.",
"Filled in from a related plant, {s}.":"Datos de una planta emparentada, {s}.", "Adjust anything you know better.":"Ajusta lo que sepas mejor.",
"No care data for this plant yet. Set a cautious cold limit, or switch low temperature warnings off; you can change it any time.":"Aún no hay datos de cuidados para esta planta. Pon un límite de frío prudente o desactiva los avisos de frío; puedes cambiarlo cuando quieras.",

/* ---- Activity history (saved in English, shown in Spanish) ---- */
"Activity history":"Historial de actividad", "Back to settings":"Volver a ajustes", "No history yet":"Aún no hay historial",
"Every watering and every move you log shows up here.":"Aquí aparece cada riego y cada cambio de sitio que registres.",
"Added":"Añadida", "Photo added":"Foto añadida", "Moved to the Vault":"Movida a la Cámara", "Shared with friends":"Compartida con amigos",
"Moved to: {spot}":"Movida a: {spot}", "Planted in the ground ({spot})":"Plantada en tierra ({spot})", "Dug up, now: {spot}":"Desenterrada, ahora: {spot}",

/* ---- Add a plant, step by step ---- */
"What plant is it?":"¿Qué planta es?", "Give it a name":"Ponle un nombre", "Where does it live?":"¿Dónde vive?", "Care":"Cuidados",
"Identification didn't work.":"La identificación no ha funcionado.",
"Fill the frame with a leaf or a flower. You can add up to 3 photos of the same plant for a better match.":"Llena el encuadre con una hoja o una flor. Puedes añadir hasta 3 fotos de la misma planta para acertar mejor.",
"Photo {n}":"Foto {n}", "Remove photo":"Quitar foto", "Take another photo":"Hacer otra foto", "Add from gallery":"Añadir de la galería", "Choose from gallery":"Elegir de la galería",
"I know what it is, skip the photo":"Sé lo que es, saltar la foto", "Identify":"Identificar", "Looking at your photo…":"Mirando tu foto…",
"No plant was recognised in this photo. Try a closer shot of a leaf or flower, or type the name below.":"No se ha reconocido ninguna planta en esta foto. Prueba con una foto más cercana de una hoja o una flor, o escribe el nombre abajo.",
"Not sure about this one. A close-up of a leaf or flower usually helps.":"No está muy claro. Una foto de cerca de una hoja o una flor suele ayudar.",
"Add another photo":"Añadir otra foto", "Tap the one that matches. Correct it below if you know better.":"Toca la que coincida. Corrígela abajo si lo sabes mejor.",
"Genus {g}":"Género {g}", "Something else":"Otra cosa", "Type the name yourself":"Escribe tú el nombre",
"Leave the species empty if you only know the genus.":"Deja la especie vacía si solo sabes el género.",
"Identification by the Pl@ntNet recognition API (my.plantnet.org).":"Identificación con la API de reconocimiento de Pl@ntNet (my.plantnet.org).",
"What do you call it? It could be the common name, or something like \"Big banana by the pond\".":"¿Cómo la llamas? Puede ser su nombre común o algo como «La platanera grande del estanque».",
"Where is it right now?":"¿Dónde está ahora?", "Through the year":"A lo largo del año", "Used for reminders to move it in autumn and out in spring.":"Sirve para recordarte meterla en otoño y sacarla en primavera.",
"{name} added":"{name} añadida", "Couldn't use that photo":"No se ha podido usar esa foto",
"Plant identification isn't available right now. Type the name below.":"La identificación de plantas no está disponible ahora. Escribe el nombre abajo.",
"Identification works when you're signed in on your site. Type the name below.":"La identificación funciona cuando has iniciado sesión en tu sitio. Escribe el nombre abajo.",

/* ---- Plant care notes ---- */
"Young plants are more tender; flowers are lost below about −5 °C.":"Las plantas jóvenes son más delicadas; las flores se pierden por debajo de unos −5 °C.",
"Spring growth is killed by late frost even when the plant is fine.":"Las heladas tardías matan los brotes de primavera aunque la planta esté bien.",
"Evergreen kinds are tender; deciduous kinds take much more cold.":"Las de hoja perenne son delicadas; las de hoja caduca aguantan mucho más frío.",
"Wet cold kills more than dry cold. Keep rain off it in winter.":"El frío húmedo mata más que el seco. Protégela de la lluvia en invierno.",
"Roots survive a few degrees of frost under thick mulch; the leaves don't.":"Las raíces aguantan unos grados bajo cero con un buen acolchado; las hojas no.",
"One of the hardiest: the roots can survive about −8 °C under thick mulch.":"De las más resistentes: las raíces aguantan unos −8 °C con un buen acolchado.",
"Keep it dry in winter.":"Mantenla seca en invierno.", "Needs very sharp drainage; wet winters kill it.":"Necesita un drenaje excelente; los inviernos húmedos la matan.",
"The top dies back in hard frost and usually regrows from the base.":"La parte aérea se seca con heladas fuertes y suele rebrotar desde la base.",
"Tubers survive in dry, well-mulched ground.":"Los tubérculos sobreviven en suelo seco y bien acolchado.",
"Hardy begonia: dies back in winter and returns late in spring.":"Begonia resistente: se seca en invierno y vuelve a finales de primavera.",
"Cut back after frost blackens the leaves; lift the rhizomes or mulch deeply.":"Córtala cuando la helada ennegrezca las hojas; saca los rizomas o acolcha bien.",
"Flowers and fruit are damaged before the tree is.":"Las flores y los frutos se dañan antes que el árbol.",
"Leaves collapse near 0 °C. Bring pots in, or cut back and mulch tubers heavily in the ground.":"Las hojas se caen cerca de 0 °C. Mete las macetas, o corta y acolcha bien los tubérculos en tierra.",
"Tie the leaves up around the growing point in a hard frost.":"Con heladas fuertes, ata las hojas hacia arriba alrededor del cogollo.",
"Keep fairly dry in winter and protect the crown from wet and frost.":"Mantenla bastante seca en invierno y protege el cogollo de la humedad y la helada.",
"The top dies at the first frost. Lift the tubers, or mulch them deeply in dry ground.":"La parte aérea muere con la primera helada. Saca los tubérculos o acólchalos bien en suelo seco.",
"Water the trunk, not just the soil. Stuff the crown with straw or cover it with fleece in hard frost.":"Riega el tronco, no solo la tierra. Con heladas fuertes, rellena el cogollo con paja o cúbrelo con manta térmica.",
"Tender. Bring inside or lift before the first frost.":"Delicada. Métela dentro o sácala de la tierra antes de la primera helada.",
"The tree is hardy, but winter flowers and young fruit are lost below about −3 °C.":"El árbol es resistente, pero las flores de invierno y los frutos jóvenes se pierden por debajo de unos −3 °C.",
"Very hardy. Keep pots from freezing solid.":"Muy resistente. Evita que las macetas se congelen del todo.",
"Young shoots die back in hard frost; established trees regrow.":"Los brotes jóvenes se secan con heladas fuertes; los árboles ya asentados rebrotan.",
"Leaves die at the first frost. Fold them over the crown and add straw before winter.":"Las hojas mueren con la primera helada. Dóblalas sobre el cogollo y añade paja antes del invierno.",
"Dies back in winter; mulch the rhizomes.":"Se seca en invierno; acolcha los rizomas.", "Hardy, but late frost kills the flower buds.":"Resistente, pero las heladas tardías matan los botones florales.",
"The top dies back around −5 °C; mulched roots survive about −10 °C and regrow.":"La parte aérea se seca hacia −5 °C; las raíces acolchadas aguantan unos −10 °C y rebrotan.",
"The trunk is damaged around −3 °C; the roots survive to about −10 °C under thick mulch. Wrap the trunk or cut it back and mulch before hard frost.":"El tronco se daña hacia −3 °C; las raíces aguantan hasta unos −10 °C con un buen acolchado. Envuelve el tronco o córtalo y acolcha antes de las heladas fuertes.",
"Like Musa basjoo: wrap or cut back the trunk and mulch the roots.":"Como la Musa basjoo: envuelve o corta el tronco y acolcha las raíces.",
"Roots survive about −10 °C under thick mulch.":"Las raíces aguantan unos −10 °C con un buen acolchado.", "Survives if the tubers sit below the ice.":"Sobrevive si los tubérculos quedan por debajo del hielo.",
"The top can die in hard frost and regrows from the roots.":"La parte aérea puede morir con heladas fuertes y rebrota desde las raíces.",
"Variegated forms are more tender.":"Las variedades variegadas son más delicadas.", "Blossom is killed by frost below about −2 °C.":"La flor muere con heladas por debajo de unos −2 °C.",
"Top can die back in hard frost and regrows from the roots. Mulch the base.":"La parte aérea puede secarse con heladas fuertes y rebrota desde las raíces. Acolcha la base.",
"Very hardy palm. Keep water out of the crown in wet winters.":"Palmera muy resistente. Evita que se acumule agua en el cogollo en inviernos húmedos.",
"Water the trunk, not just the soil. Stuff the crown with straw or cover it with fleece below −5 °C.":"Riega el tronco, no solo la tierra. Por debajo de −5 °C, rellena el cogollo con paja o cúbrelo con manta térmica.",
"Tender. Inside once nights drop below about 10 °C.":"Delicada. Dentro en cuanto las noches bajen de unos 10 °C.",
"Hardy fan palm. Dislikes wet roots in pots over winter.":"Palmera de abanico resistente. No le gustan las raíces encharcadas en maceta en invierno.",
"Very thirsty in summer. Keep cool and fairly dry indoors in winter.":"Muy sedienta en verano. En invierno, dentro, fresca y bastante seca.",


/* ---- The circle ---- */
"Friends, plants, inspiration":"Amigos, plantas, inspiración", "{n} new request":"{n} solicitud nueva", "{n} new requests":"{n} solicitudes nuevas",
"{n} new reaction or comment":"{n} reacción o comentario nuevo", "{n} new reactions and comments":"{n} reacciones y comentarios nuevos",
"Couldn't get your link. Check your connection.":"No se ha podido obtener tu enlace. Revisa la conexión.",
"{n} plant shared":"{n} planta compartida", "{n} plants shared":"{n} plantas compartidas", "nothing shared yet":"aún no comparte nada",
"More for {name}":"Más opciones para {name}", "Searching…":"Buscando…",
"Nobody found. People only show up here if they switched on \"Let people find me\". If they haven't, send them your link instead.":"No se ha encontrado a nadie. Solo aparecen quienes han activado «Dejar que me encuentren». Si no lo han hecho, mándales tu enlace.",
"Visit":"Visitar", "Requested":"Solicitado", "Accept":"Aceptar", "Sign in first":"Inicia sesión primero", "Friends need an Alvor account.":"Para tener amigos necesitas una cuenta de Alvor.",
"Friend requests":"Solicitudes de amistad", "What's new":"Novedades", "Your friend link":"Tu enlace de amistad",
"Send it to people you know. Whoever opens it becomes your friend straight away, and if they don't have Alvor yet, it's their invitation too.":"Mándaselo a gente que conozcas. Quien lo abra se hace tu amigo al momento y, si aún no tiene Alvor, también le sirve de invitación.",
"Share my link":"Compartir mi enlace", "Hide QR code":"Ocultar código QR", "QR code":"Código QR", "QR code of your friend link":"Código QR de tu enlace de amistad",
"Your friend scans it with their phone's camera.":"Tu amigo lo escanea con la cámara del móvil.", "Getting your link…":"Obteniendo tu enlace…",
"Sent it to the wrong person?":"¿Se lo has mandado a quien no era?", "Reset my link":"Renueva tu enlace", "and the old one stops working.":"y el anterior deja de funcionar.",
"Find people":"Buscar personas", "Name or @username":"Nombre o @usuario", "Find people by name or @username":"Buscar personas por nombre o @usuario",
"You're hidden from search: only people with your link can add you.":"No apareces en las búsquedas: solo te puede añadir quien tenga tu enlace.",
"Let people find me":"Dejar que me encuentren", "Your friends":"Tus amigos", "No friends yet. Share your link to start your circle.":"Aún no tienes amigos. Comparte tu enlace para empezar tu círculo.",
"Waiting for an answer":"Esperando respuesta", "Blocked ({n})":"Bloqueados ({n})", "Unblock":"Desbloquear",
"Be my friend on Alvor, the app I use for my plants: {url}":"Hazte mi amigo en Alvor, la app que uso para mis plantas: {url}",
"People can find you by name":"Ahora te pueden encontrar por tu nombre", "Request sent":"Solicitud enviada", "Request declined":"Solicitud rechazada", "Request cancelled":"Solicitud cancelada",
"You and {name} are friends":"{name} y tú sois amigos", "You and your friend are friends":"Ya sois amigos",
"Remove {name} from your friends? You stop seeing each other's gardens. They aren't told.":"¿Quitar a {name} de tus amigos? Dejaréis de ver vuestros jardines. No se le avisa.",
"{name} removed":"{name} ya no está entre tus amigos",
"Block {name}? If you're friends, that ends, and neither of you can see, find or add the other. They aren't told.":"¿Bloquear a {name}? Si sois amigos, dejaréis de serlo, y ninguno podrá ver, buscar ni añadir al otro. No se le avisa.",
"{name} blocked":"Has bloqueado a {name}", "{name} unblocked. You can add each other again.":"Has desbloqueado a {name}. Podéis volver a añadiros.",
"Reset your friend link? The link and QR code you shared before stop working. People who are already your friends stay friends.":"¿Renovar tu enlace de amistad? El enlace y el código QR que compartiste dejarán de funcionar. Quienes ya son tus amigos lo seguirán siendo.",
"You have a new link":"Ya tienes un enlace nuevo", "Visit their garden":"Visitar su jardín", "Remove from friends":"Quitar de amigos", "Block":"Bloquear", "Decline":"Rechazar", "Report…":"Denunciar…",
"{n} photos":"{n} fotos", "Back to friends":"Volver a amigos", "Opening the garden…":"Abriendo el jardín…", "Couldn't open this garden":"No se ha podido abrir este jardín",
"You're not friends":"No sois amigos", "Only friends can visit {name}'s garden.":"Solo sus amigos pueden visitar el jardín de {name}.",
"{name} hasn't shared any plants yet":"{name} aún no ha compartido ninguna planta", "Their plants show up here as soon as they share some with friends.":"Sus plantas aparecerán aquí en cuanto comparta alguna con sus amigos.",
"No photos shared yet":"Aún no hay fotos compartidas", "Something wrong?":"¿Algo va mal?", "Report this plant":"Denunciar esta planta", "Report this photo":"Denunciar esta foto",
"the plant \"{name}\"":"la planta «{name}»", "this photo of \"{name}\"":"esta foto de «{name}»",

/* ---- Reactions, comments, what's new ---- */
"Love it":"Me encanta", "Growing well":"Crece bien", "So pretty":"Qué bonita", "Impressive":"Impresionante", "Needs water?":"¿Necesita agua?", "Too much water?":"¿Demasiada agua?",
"Your account is switched off.":"Tu cuenta está desactivada.", "This isn't shared with you any more.":"Esto ya no se comparte contigo.",
"No reactions yet.":"Aún no hay reacciones.", "React":"Reaccionar", "and {n} more":"y {n} más", "No comments yet.":"Aún no hay comentarios.",
"No comments yet. Say something nice.":"Aún no hay comentarios. Di algo bonito.", "Show {n} earlier":"Ver {n} anteriores", "More for this comment":"Más opciones para este comentario",
"{n} comment":"{n} comentario", "{n} comments":"{n} comentarios", "Comment":"Comentar", "Comments":"Comentarios", "Write a comment…":"Escribe un comentario…", "Write a comment":"Escribe un comentario",
"Send":"Enviar", "Delete my comment":"Borrar mi comentario", "Remove from my garden":"Quitar de mi jardín", "Report this comment…":"Denunciar este comentario…", "this comment":"este comentario",
"Delete your comment?":"¿Borrar tu comentario?", "Remove {name}'s comment from your garden? They aren't told.":"¿Quitar el comentario de {name} de tu jardín? No se le avisa.",
"Comment deleted":"Comentario borrado", "Couldn't open this":"No se ha podido abrir", "Not shared any more":"Ya no se comparte", "This isn't shared any more":"Esto ya no se comparte",
"The plant was deleted, or moved back to its owner's Vault.":"La planta se ha borrado o ha vuelto a la Cámara de su dueño.",
"You're no longer friends with the owner of this garden.":"Ya no eres amigo del dueño de este jardín.", "Open the plant":"Abrir la planta", "Visit {name}'s garden":"Visitar el jardín de {name}",
"{actor} added a photo of {thing}":"{actor} ha añadido una foto de {thing}", "{actor} added {n} photos of {thing}":"{actor} ha añadido {n} fotos de {thing}",
"{actor} reacted {emoji} to {thing}":"{actor} ha reaccionado {emoji} a {thing}", "{actor} commented on {thing}":"{actor} ha comentado en {thing}",
"{actor} replied on {thing}":"{actor} ha respondido en {thing}", "a friend":"un amigo", "{actor} also commented on {thing}":"{actor} también ha comentado en {thing}",
"Nothing yet. Reactions and comments on your plants, replies to your comments and friends' new photos show up here.":"Aún no hay nada. Aquí aparecen las reacciones y comentarios a tus plantas, las respuestas a tus comentarios y las fotos nuevas de tus amigos.",
"Show more":"Ver más",

/* ---- Locations: your own pictures ---- */
"{place} photo":"Foto de {place}", "Back to the {style} picture":"Volver a la imagen del estilo {style}", "Back to the style picture":"Volver a la imagen del estilo",
"Friends see this photo on your {place} tile when they visit your garden.":"Tus amigos ven esta foto en tu recuadro de {place} cuando visitan tu jardín.",
"{place} photo saved":"Foto de {place} guardada", "Your photo":"Tu foto",

/* ---- More: profile ---- */
"Your profile":"Tu perfil", "Your name":"Tu nombre", "How friends see you, e.g. Diogo or Ana G.":"Cómo te ven tus amigos, p. ej. Diogo o Ana G.",
"3 to 24 letters, numbers, dots or dashes, with no spaces.":"De 3 a 24 letras, números, puntos o guiones, sin espacios.", "Save profile":"Guardar perfil",
"Friends see your name, @username and photo. Never your email.":"Tus amigos ven tu nombre, tu @usuario y tu foto. Nunca tu correo.",
"Your profile, settings and account":"Tu perfil, ajustes y cuenta", "Edit profile":"Editar perfil", "Change photo":"Cambiar foto",
"Add your name":"Añade tu nombre", "Keep your name under 40 characters":"El nombre debe tener menos de 40 caracteres",
"Use 3 to 24 letters, numbers, dots or dashes for your @username":"Usa de 3 a 24 letras, números, puntos o guiones para tu @usuario",
"That @username is already taken":"Ese @usuario ya está cogido", "That @username can't be used. Try letters and numbers only.":"Ese @usuario no se puede usar. Prueba solo con letras y números.",
"Profile saved":"Perfil guardado", "Photo saved":"Foto guardada", "Couldn't save the photo. Try again.":"No se ha podido guardar la foto. Vuelve a intentarlo.",
"Remove your profile photo?":"¿Quitar tu foto de perfil?", "Photo removed":"Foto quitada", "Couldn't remove it. Check your connection.":"No se ha podido quitar. Revisa la conexión.",

/* ---- More: appearance and language ---- */
"Appearance":"Apariencia", "Style":"Estilo", "Changes the backdrop and the pictures of your places.":"Cambia el fondo y las imágenes de tus lugares.", "Backdrop":"Fondo",
"Move the light":"Mover la luz", "Remove my photo":"Quitar mi foto", "Accent colour":"Color de acento", "Light or dark":"Claro u oscuro",
"Classic":"Clásico", "Modern":"Moderno", "Futuristic":"Futurista", "Fern":"Helecho", "Moss":"Musgo", "Plum":"Ciruela", "Rose":"Rosa", "Graphite":"Grafito",
"Automatic":"Automático", "Light":"Claro", "Dark":"Oscuro", "My photo":"Mi foto",
"Friends see this photo when they visit your garden, with your style's pictures on their tiles.":"Tus amigos ven esta foto cuando visitan tu jardín, con las imágenes de tu estilo en sus recuadros.",
"Friends see your style when they visit your garden.":"Tus amigos ven tu estilo cuando visitan tu jardín.",
"Change: my plant photos":"Cambiar: fotos de mis plantas", "From my plant photos":"De las fotos de mis plantas", "Change: from the phone":"Cambiar: desde el móvil", "From the phone":"Desde el móvil",
"This plant is in your Vault, but friends who visit your garden will see this photo as its backdrop.":"Esta planta está en tu Cámara, pero tus amigos verán esta foto como fondo cuando visiten tu jardín.",
"Friends who visit your garden will see this photo.":"Tus amigos verán esta foto cuando visiten tu jardín.", "Use this photo":"Usar esta foto", "Backdrop saved":"Fondo guardado",
"Couldn't save the photo. Check your connection and try again.":"No se ha podido guardar la foto. Revisa la conexión y vuelve a intentarlo.", "Saving photo…":"Guardando la foto…",
"Couldn't open the photo. Check your connection.":"No se ha podido abrir la foto. Revisa la conexión.",
"Remove your backdrop photo? The app goes back to your style's photo.":"¿Quitar tu foto de fondo? La app vuelve a la foto de tu estilo.",
"Choose a photo":"Elige una foto", "Your plant photos, newest first.":"Las fotos de tus plantas, de la más nueva a la más antigua.", "Where is the light?":"¿Dónde está la luz?",
"Tap the brightest spot, like the sun or a bright window. A soft glow breathes there on clear days, and the photo keeps that spot in view on every screen.":"Toca el punto más luminoso, como el sol o una ventana. Los días despejados un brillo suave respira ahí, y la foto mantiene ese punto a la vista en todas las pantallas.",
"Glow on clear days":"Brillo los días despejados", "Untick it if the photo has no sun or bright spot.":"Desmárcalo si la foto no tiene sol ni un punto luminoso.", "Your backdrop photo":"Tu foto de fondo",
"Language":"Idioma", "Follows the phone: {lang}.":"Sigue al móvil: {lang}.", "Notifications and emails from Alvor use it too.":"Los avisos y correos de Alvor también lo usan.",

/* ---- More: sharing, home, location ---- */
"Sharing and privacy":"Compartir y privacidad", "New plants you add are visible to":"Las plantas nuevas que añadas son visibles para", "New plants are visible to":"Las plantas nuevas son visibles para",
"Choose which plants friends see":"Elegir qué plantas ven tus amigos",
"When it's on, people can find you by your name or @username and send you a friend request. When it's off, only people you give your friend link to can add you.":"Si está activado, la gente puede encontrarte por tu nombre o @usuario y mandarte una solicitud de amistad. Si no, solo te puede añadir quien tenga tu enlace de amistad.",
"Friends see new plants as soon as you add them.":"Tus amigos ven las plantas nuevas en cuanto las añades.", "New plants go to your Vault. Only you see them until you share them.":"Las plantas nuevas van a tu Cámara. Solo las ves tú hasta que las compartas.",
"Only people with your link can add you":"Solo te puede añadir quien tenga tu enlace",
"Your home":"Tu casa", "Home type":"Tipo de casa", "House with garden":"Casa con jardín", "Apartment":"Piso", "Rain reaches my balcony":"La lluvia llega a mi balcón",
"Tick it if the balcony is open to the sky. Then rain counts as watering for balcony plants.":"Márcalo si el balcón está al descubierto. Así la lluvia cuenta como riego para las plantas del balcón.",
"Spots: inside (window, low light, grow cabinet) and the balcony (sun, partial sun, shade).":"Sitios: dentro (ventana, poca luz, armario de cultivo) y el balcón (sol, semisombra, sombra).",
"Spots: the house, the porch, outside in the garden and the greenhouse.":"Sitios: la casa, el porche, fuera en el jardín y el invernadero.",
"{n} plant is in a spot that doesn't exist here. Move it from the Plants tab.":"{n} planta está en un sitio que aquí no existe. Muévela desde la pestaña Plantas.",
"{n} plants are in spots that don't exist here. Move them from the Plants tab.":"{n} plantas están en sitios que aquí no existen. Muévelas desde la pestaña Plantas.",
"Home type saved":"Tipo de casa guardado", "The forecast and all the alerts use this location.":"La previsión y todos los avisos usan esta ubicación.", "Which location to use":"Qué ubicación usar",
"My current location":"Mi ubicación actual", "Saved place":"Lugar guardado", "Update now":"Actualizar ahora",
"Updates by itself whenever you open the app. Notifications use the last place the app saw you.":"Se actualiza sola cada vez que abres la app. Los avisos usan el último lugar donde te vio la app.",
"Change the saved place":"Cambiar el lugar guardado", "Search a town, e.g. Lekunberri":"Busca un pueblo, p. ej. Lekunberri", "Save where I am now":"Guardar dónde estoy ahora",
"Enter coordinates":"Introducir coordenadas", "Latitude":"Latitud", "Longitude":"Longitud", "Save this place":"Guardar este lugar",
"This browser can't share its location.":"Este navegador no puede compartir su ubicación.",
"Location access is blocked. Allow it for this site in Chrome's settings.":"El acceso a la ubicación está bloqueado. Permítelo para este sitio en los ajustes de Chrome.",
"Couldn't get your location right now.":"No se ha podido obtener tu ubicación ahora.", "Finding you…":"Buscando dónde estás…", "Checked":"Comprobado",
"Not found yet. Tap Update now.":"Aún no se ha encontrado. Toca Actualizar ahora.", "Saved {name}":"Guardado: {name}",
"No places found. Try another spelling, or enter coordinates below.":"No se ha encontrado ningún lugar. Prueba a escribirlo de otra forma o introduce las coordenadas abajo.",
"Search isn't working right now. Enter coordinates below.":"La búsqueda no funciona ahora. Introduce las coordenadas abajo.", "Check the latitude and longitude":"Revisa la latitud y la longitud",
"My place":"Mi casa",

/* ---- More: alert rules, notifications ---- */
"Alert rules":"Reglas de los avisos", "Low temperature margin °C":"Margen de frío °C", "Warn when the forecast gets this close to a plant's limit.":"Avisar cuando la previsión se acerque tanto al límite de una planta.",
"Greenhouse warmer by °C":"El invernadero, más cálido en °C", "How much warmer your greenhouse stays than outside at night.":"Cuánto más cálido que fuera se queda tu invernadero por la noche.",
"Heat °C":"Calor °C", "Gusts km/h":"Rachas km/h", "Rain counts as watering, mm":"Lluvia que cuenta como riego, mm", "Save settings":"Guardar ajustes", "Settings saved":"Ajustes guardados",
"Low temperature warnings per plant":"Avisos de frío por planta", "On for {n} of {total}":"Activados en {n} de {total}",
"Untick plants you've already protected for the winter, or that take far more cold than your garden gets. Heat, wind and watering reminders still come for every plant.":"Desmarca las plantas que ya has protegido para el invierno o que aguantan mucho más frío del que hace en tu jardín. Los avisos de calor, viento y riego siguen llegando para todas.",
"Tick all":"Marcar todas", "Untick all":"Desmarcar todas", "no cold limit set":"sin límite de frío", "Set the lowest temperature {name} takes first":"Pon primero la mínima que aguanta {name}",
"{n} plant has no cold limit yet":"{n} planta aún no tiene límite de frío", "{n} plants have no cold limit yet":"{n} plantas aún no tienen límite de frío",
"Notifications":"Avisos", "Morning summary at":"Resumen de la mañana a las", "Evening cold check at":"Aviso de frío de la tarde a las", "Send the evening cold check":"Mandar el aviso de frío de la tarde",
"Only arrives when a plant is at risk that night.":"Solo llega cuando alguna planta está en riesgo esa noche.", "Reactions and comments from friends":"Reacciones y comentarios de amigos",
"When someone reacts to or comments on your plants, or replies where you commented.":"Cuando alguien reacciona o comenta en tus plantas, o responde donde has comentado.",
"Turn on notifications":"Activar los avisos", "Send a test":"Mandar una prueba",
"Notifications work once the app is opened from your site in Chrome.":"Los avisos funcionan cuando la app se abre desde tu sitio en Chrome.",
"Notifications are on for this phone.":"Los avisos están activados en este móvil.", "Notifications are off for this phone.":"Los avisos están desactivados en este móvil.",
"This browser can't receive notifications. Open the app from your site in Chrome.":"Este navegador no puede recibir avisos. Abre la app desde tu sitio en Chrome.",
"Notifications are blocked. Allow them for this site in Chrome's settings, then try again.":"Los avisos están bloqueados. Permítelos para este sitio en los ajustes de Chrome y vuelve a intentarlo.",
"Turning on…":"Activando…", "Notifications on":"Avisos activados", "Couldn't turn on notifications. Try again in a moment.":"No se han podido activar los avisos. Vuelve a intentarlo en un momento.",
"Sending a test…":"Mandando una prueba…", "Test sent. It should arrive in a few seconds.":"Prueba enviada. Debería llegar en unos segundos.",
"This phone isn't signed up for notifications yet. Tap Turn on notifications first.":"Este móvil aún no está apuntado a los avisos. Toca primero Activar los avisos.",
"Couldn't send the test. Try again in a moment.":"No se ha podido mandar la prueba. Vuelve a intentarlo en un momento.",

/* ---- More: history, backup, data, reset ---- */
"Every watering, move and photo, for all your plants. Each plant's own history is also in its edit screen.":"Cada riego, cambio de sitio y foto de todas tus plantas. El historial de cada planta también está en su pantalla de edición.",
"Open history":"Abrir historial", "Backup":"Copia de seguridad",
"Your plants and photos are saved in your account. You can also export a backup file to keep a copy of your own. The file grows as you add photos.":"Tus plantas y fotos se guardan en tu cuenta. También puedes exportar un archivo de copia para tener una copia tuya. El archivo crece a medida que añades fotos.",
"Export backup":"Exportar copia", "Import backup":"Importar copia", "Replace what's here with {n} plants from the backup?":"¿Sustituir lo que hay aquí por las {n} plantas de la copia?",
"Plants imported, but the photos couldn't be saved":"Plantas importadas, pero no se han podido guardar las fotos", "Backup imported":"Copia importada", "That file isn't a garden backup":"Ese archivo no es una copia de un jardín",
"Your data and privacy":"Tus datos y privacidad", "Get everything Alvor keeps about you in one file: your plants, notes, history, photos, friends and settings.":"Descarga en un archivo todo lo que Alvor guarda sobre ti: tus plantas, notas, historial, fotos, amigos y ajustes.",
"Download my data":"Descargar mis datos", "Privacy policy":"Política de privacidad", "Delete my account":"Borrar mi cuenta",
"Deletes your account and everything in it, from every phone and for good. Download your data first if you'd like a copy.":"Borra tu cuenta y todo lo que contiene, de todos los móviles y para siempre. Descarga antes tus datos si quieres una copia.",
"Reset":"Empezar de cero", "Delete all plants and history":"Borrar todas las plantas y el historial",
"Delete all plants and history, on this phone and in your account? Export a backup first if you might want them back.":"¿Borrar todas las plantas y el historial, en este móvil y en tu cuenta? Exporta antes una copia si puede que las quieras recuperar.",
"Delete all plants and history on this device? Export a backup first if you might want them back.":"¿Borrar todas las plantas y el historial de este dispositivo? Exporta antes una copia si puede que las quieras recuperar.",
"Everything deleted":"Todo borrado", "Couldn't save. Export a backup to be safe.":"No se ha podido guardar. Exporta una copia por seguridad.",
"Saving the latest changes…":"Guardando los últimos cambios…", "Collecting your data…":"Reuniendo tus datos…", "Adding photos: {n} of {total}…":"Añadiendo fotos: {n} de {total}…",
"Making the file…":"Creando el archivo…", "Done: {n} photo and all your details, {mb} MB.":"Listo: {n} foto y todos tus datos, {mb} MB.", "Done: {n} photos and all your details, {mb} MB.":"Listo: {n} fotos y todos tus datos, {mb} MB.",
"{n} photo couldn't be fetched; try again later.":"No se ha podido obtener {n} foto; vuelve a intentarlo más tarde.", "{n} photos couldn't be fetched; try again later.":"No se han podido obtener {n} fotos; vuelve a intentarlo más tarde.",
"Couldn't collect your data. Check your connection and try again.":"No se han podido reunir tus datos. Revisa la conexión y vuelve a intentarlo.",
"Delete your account?":"¿Borrar tu cuenta?", "This deletes, from every phone and for good:":"Esto borra, de todos los móviles y para siempre:",
"your plants, notes and history":"tus plantas, notas e historial", "all your photos, your profile photo and your backdrop photo":"todas tus fotos, tu foto de perfil y tu foto de fondo",
"your profile, friends, requests and friend link":"tu perfil, amigos, solicitudes y enlace de amistad", "reactions and comments you wrote, and the ones on your garden":"las reacciones y comentarios que escribiste, y los de tu jardín",
"It can't be undone. Your friends aren't told; you simply disappear from their list. Want a copy first? Close this and tap Download my data.":"No se puede deshacer. A tus amigos no se les avisa; simplemente desapareces de su lista. ¿Quieres una copia antes? Cierra esto y toca Descargar mis datos.",
"Type your password to confirm":"Escribe tu contraseña para confirmar", "Keep my account":"Mantener mi cuenta", "Type your password first.":"Escribe primero tu contraseña.", "Deleting…":"Borrando…",
"Your account and everything in it have been deleted. Thank you for growing with Alvor.":"Tu cuenta y todo lo que contenía se han borrado. Gracias por crecer con Alvor.",

/* ---- Account ---- */
"Account":"Cuenta", "Invite a friend":"Invitar a un amigo", "Change password":"Cambiar contraseña", "Sign out":"Cerrar sesión", "Current password":"Contraseña actual",
"New password":"Nueva contraseña", "Password":"Contraseña", "At least 8 characters.":"Al menos 8 caracteres.", "Save new password":"Guardar nueva contraseña",
"Accounts work once the app is opened from your site.":"Las cuentas funcionan cuando la app se abre desde tu sitio.", ", owner of Alvor":", dueño de Alvor",
"Signed in as {who}.":"Sesión iniciada como {who}.", "Not signed in.":"No has iniciado sesión.",
"Your account has been switched off by the owner of Alvor. Your garden still works for you, but nobody else can see it, find you or add you.":"El dueño de Alvor ha desactivado tu cuenta. Tu jardín te sigue funcionando, pero nadie más puede verlo, encontrarte ni añadirte.",
"Send this code to your friend, together with the address of Alvor:":"Manda este código a tu amigo, junto con la dirección de Alvor:",
"It works once, until {date}. They tap Create account and enter it there.":"Sirve una vez, hasta el {date}. Tiene que tocar Crear cuenta y escribirlo allí.", "Copy message":"Copiar mensaje",
"Join me on Alvor, the app I use for my plants. Get it here: {url} , then tap \"Create account\" and use this invite code: {code}":"Únete a mí en Alvor, la app que uso para mis plantas. Descárgala aquí: {url} , toca «Crear cuenta» y usa este código de invitación: {code}",
"The new password needs at least 8 characters.":"La nueva contraseña necesita al menos 8 caracteres.", "The current password is wrong.":"La contraseña actual no es correcta.",
"That's the password you already have.":"Esa ya es tu contraseña.", "Couldn't change the password":"No se ha podido cambiar la contraseña",
"Password changed. Other phones will need to sign in again.":"Contraseña cambiada. En los demás móviles tendrás que volver a iniciar sesión.",
"Couldn't reach Alvor. Changes stay on this phone and are saved next time.":"No se ha podido conectar con Alvor. Los cambios se quedan en este móvil y se guardarán la próxima vez.",
"Please sign in again.":"Vuelve a iniciar sesión.", "Saved to your account at {time}.":"Guardado en tu cuenta a las {time}.", "Saving photos…":"Guardando fotos…", "Getting photos…":"Descargando fotos…",
"Some photos aren't saved to your account yet. Alvor tries again next time.":"Algunas fotos aún no están guardadas en tu cuenta. Alvor lo volverá a intentar la próxima vez.",
"This phone has {n} plant. Move it into this account?":"Este móvil tiene {n} planta. ¿Pasarla a esta cuenta?", "This phone has {n} plants. Move them into this account?":"Este móvil tiene {n} plantas. ¿Pasarlas a esta cuenta?",
"Welcome, {name}":"Hola, {name}", "You're signed out.":"Has cerrado la sesión.", "Sign out on this phone? Your garden stays saved in your account.":"¿Cerrar sesión en este móvil? Tu jardín sigue guardado en tu cuenta.",
"Couldn't use that link. Check your connection and open it again.":"No se ha podido usar ese enlace. Revisa la conexión y vuelve a abrirlo.",
"Reports":"Denuncias", "Only you see this, as the owner of Alvor. People's reports land here; the person reported isn't told who sent them.":"Solo lo ves tú, como dueño de Alvor. Aquí llegan las denuncias; a la persona denunciada no se le dice quién las mandó.",

/* ---- Sign in ---- */
"Your plants. Your spaces. Together.":"Tus plantas. Tus espacios. Juntos.", "Sign in":"Iniciar sesión", "Create account":"Crear cuenta", "Send me a code":"Mandarme un código",
"Sign in to see your garden.":"Inicia sesión para ver tu jardín.", "Create your own garden. You need an invite code or a friend's link.":"Crea tu propio jardín. Necesitas un código de invitación o el enlace de un amigo.",
"Enter the email of your account. We'll send you a code to set a new password.":"Escribe el correo de tu cuenta. Te mandaremos un código para poner una contraseña nueva.",
"If {email} has an Alvor account, a code is on its way. It works for an hour. Check the spam folder too.":"Si {email} tiene una cuenta de Alvor, el código ya va de camino. Sirve durante una hora. Mira también en la carpeta de spam.",
"By creating an account you agree to how Alvor looks after your data, described in the {link}privacy policy{end}.":"Al crear una cuenta aceptas cómo cuida Alvor tus datos, descrito en la {link}política de privacidad{end}.",
"Invite code or link":"Código o enlace de invitación", "An invite code, or the link a friend sent you. Setting Alvor up for the first time? Use your APP_KEY.":"Un código de invitación o el enlace que te mandó un amigo. ¿Es la primera vez que configuras Alvor? Usa tu APP_KEY.",
"Email":"Correo", "What friends will find you by: 3 to 24 letters, numbers, dots or dashes.":"Así te encontrarán tus amigos: de 3 a 24 letras, números, puntos o guiones.",
"Code from the email":"Código del correo", "Forgot your password?":"¿Has olvidado la contraseña?", "Send a new code":"Mandar un código nuevo", "Back to sign in":"Volver a iniciar sesión",
"Fill in your email and password.":"Escribe tu correo y tu contraseña.", "Wrong email or password.":"Correo o contraseña incorrectos.", "Couldn't sign in. Try again.":"No se ha podido iniciar sesión. Vuelve a intentarlo.",
"Enter the email of your account.":"Escribe el correo de tu cuenta.", "A code was sent a moment ago. Wait a minute before asking for another one.":"Se acaba de mandar un código. Espera un minuto antes de pedir otro.",
"Couldn't send the code. Try again in a while.":"No se ha podido mandar el código. Vuelve a intentarlo dentro de un rato.", "A new code is on its way. Only the newest code works.":"Va de camino un código nuevo. Solo sirve el más reciente.",
"Enter the code from the email.":"Escribe el código del correo.", "That code doesn't work. Check it, or send a new one.":"Ese código no sirve. Revísalo o pide uno nuevo.",
"That's the password you already have. You can just sign in with it.":"Esa ya es tu contraseña. Puedes iniciar sesión con ella.", "Choose a longer or less common password.":"Elige una contraseña más larga o menos común.",
"Couldn't save the new password. Try again.":"No se ha podido guardar la nueva contraseña. Vuelve a intentarlo.",
"New password saved. Other phones will need to sign in again.":"Nueva contraseña guardada. En los demás móviles tendrás que volver a iniciar sesión.",
"Something went wrong. Try again.":"Algo ha fallado. Vuelve a intentarlo.",
"A friend invited you. Create your account to join their circle.":"Un amigo te ha invitado. Crea tu cuenta para unirte a su círculo.",
"Alvor has a new home. Create a new account with the invite you received, or sign in if you already did. The plants on this phone come with you.":"Alvor tiene una casa nueva. Crea una cuenta nueva con la invitación que recibiste, o inicia sesión si ya lo hiciste. Las plantas de este móvil se vienen contigo.",

/* ---- Welcome setup and sharing ---- */
"Welcome, {name}!":"¡Hola, {name}!", "Welcome!":"¡Hola!", "Where do your plants live?":"¿Dónde viven tus plantas?", "Garden, porch and greenhouse":"Jardín, porche e invernadero",
"Inside and a balcony":"Interior y un balcón", "Does rain reach your balcony?":"¿Llega la lluvia a tu balcón?", "If it does, rain counts as watering for balcony plants.":"Si llega, la lluvia cuenta como riego para las plantas del balcón.",
"No, it's covered":"No, está cubierto", "Where is your balcony?":"¿Dónde está tu balcón?", "Where is your garden?":"¿Dónde está tu jardín?",
"The forecast and all the alerts use this place.":"La previsión y todos los avisos usan este lugar.", "That's right":"Correcto", "Choose another place":"Elegir otro lugar",
"Use my current location":"Usar mi ubicación actual", "Search a town":"Busca un pueblo", "e.g. Lekunberri":"p. ej. Lekunberri", "No places found. Try another spelling.":"No se ha encontrado ningún lugar. Prueba a escribirlo de otra forma.",
"Search isn't working right now. Check your connection.":"La búsqueda no funciona ahora. Revisa la conexión.", "Search your town instead.":"Busca tu pueblo.",
"Sharing with friends":"Compartir con amigos", "When you have friends on Alvor, who should see the plants you add?":"Cuando tengas amigos en Alvor, ¿quién debería ver las plantas que añadas?",
"Get alerts":"Recibe avisos", "Every morning at 08:00":"Cada mañana a las 08:00", "A short summary of what your plants need today.":"Un breve resumen de lo que necesitan hoy tus plantas.",
"In the evening at 19:00":"Por la tarde a las 19:00", "A warning, only when a plant could get too cold that night.":"Un aviso, solo cuando alguna planta pueda pasar demasiado frío esa noche.",
"Notifications work when the app is opened from your site in Chrome. You can turn them on later in Settings.":"Los avisos funcionan cuando la app se abre desde tu sitio en Chrome. Puedes activarlos más tarde en Ajustes.",
"You can change the times in Settings.":"Puedes cambiar las horas en Ajustes.", "You're all set":"Todo listo", "Start with one plant. Take a photo and the app suggests what it is.":"Empieza con una planta. Hazle una foto y la app te sugiere qué es.",
"Add my first plant":"Añadir mi primera planta", "Friends see":"Tus amigos ven", "Name, species, spot, photos and how it's growing":"Nombre, especie, sitio, fotos y cómo crece",
"Never shared":"Nunca se comparte", "Your notes, watering and exact location":"Tus notas, riegos y ubicación exacta", "They see the plants you add":"Ven las plantas que añades",
"New plants go to your Vault. Share them one by one.":"Las plantas nuevas van a tu Cámara. Compártelas una a una.", "You can change it for any plant, any time, in its edit screen.":"Puedes cambiarlo para cualquier planta, cuando quieras, en su pantalla de edición.",
"Couldn't save that to your account. Try again in Settings.":"No se ha podido guardar en tu cuenta. Vuelve a intentarlo en Ajustes.",
"Share your garden with friends":"Comparte tu jardín con tus amigos", "Friends on Alvor can now see the plants you choose.":"Ahora tus amigos en Alvor pueden ver las plantas que elijas.",
"For now all your plants are in your Vault: only you see them.":"De momento todas tus plantas están en tu Cámara: solo las ves tú.",
"{n} of your {total} plants are in your Vault: only you see them.":"{n} de tus {total} plantas están en tu Cámara: solo las ves tú.",
"Share {n} plant":"Compartir {n} planta", "Share all {n} plants":"Compartir las {n} plantas", "Share {n} plants":"Compartir {n} plantas", "Choose which":"Elegir cuáles", "Not now":"Ahora no",
"Choose what friends see":"Elige qué ven tus amigos", "Ticked plants are visible to friends. The rest stay in your Vault, with all their alerts.":"Las plantas marcadas las ven tus amigos. El resto se queda en tu Cámara, con todos sus avisos.",
"Keep them all in the Vault":"Dejarlas todas en la Cámara", "And the plants you add from now on?":"¿Y las plantas que añadas a partir de ahora?",
"Pick who sees new plants. You can still change each one.":"Elige quién ve las plantas nuevas. Aun así puedes cambiar cada una.",
"New plants will be visible to friends":"Las plantas nuevas serán visibles para tus amigos", "New plants will go to your Vault":"Las plantas nuevas irán a tu Cámara",
"{n} plant visible to friends":"{n} planta visible para tus amigos", "{n} plants visible to friends":"{n} plantas visibles para tus amigos", "All plants are in your Vault":"Todas las plantas están en tu Cámara",
"Nothing changed":"No ha cambiado nada",

/* ---- Reporting and the owner's Reports ---- */
"Report":"Denunciar", "What's wrong":"Qué pasa", "Anything to add?":"¿Algo que añadir?", "(optional)":"(opcional)", "Also block":"Bloquear también a",
"You stop seeing each other, and they can't find or add you. They aren't told.":"Dejáis de veros, y no puede encontrarte ni añadirte. No se le avisa.", "Send report":"Mandar denuncia",
"Rude, offensive or hateful":"Grosero, ofensivo o de odio", "Bullying or harassment":"Acoso", "Nudity or sexual content":"Desnudos o contenido sexual", "Spam or a fake account":"Spam o cuenta falsa",
"Report {name}":"Denunciar a {name}", "Report a photo":"Denunciar una foto", "Report a comment":"Denunciar un comentario", "Report a plant":"Denunciar una planta",
"What's wrong with {name}'s profile or garden?":"¿Qué pasa con el perfil o el jardín de {name}?", "What's wrong with {what}?":"¿Qué pasa con {what}?",
"Reports go to the owner of Alvor, who looks at each one. {name} isn't told who sent it.":"Las denuncias le llegan al dueño de Alvor, que las revisa una a una. A {name} no se le dice quién la mandó.",
"Report sent, and {name} is blocked":"Denuncia enviada, y has bloqueado a {name}", "Report sent. Thank you.":"Denuncia enviada. Gracias.",
"{n} new report to look at, in Settings":"{n} denuncia nueva por revisar, en Ajustes", "{n} new reports to look at, in Settings":"{n} denuncias nuevas por revisar, en Ajustes",
"Couldn't load the reports. Check your connection.":"No se han podido cargar las denuncias. Revisa la conexión.", "{n} open":"{n} abiertas", "a deleted account":"una cuenta borrada",
"switched off":"desactivada", "The reported photo":"La foto denunciada", "No reason given":"Sin motivo", "reported by {who}":"denunciado por {who}", "{n} open reports about them":"{n} denuncias abiertas sobre esta persona",
"Mark as handled":"Marcar como resuelta", "Switch off their account":"Desactivar su cuenta", "No open reports.":"No hay denuncias abiertas.", "Switched-off accounts":"Cuentas desactivadas",
"Switch back on":"Volver a activar", "this account":"esta cuenta",
"Switch off {name}? Nobody can see their garden, profile or comments, find them or add them, until you switch it back on. Their open reports are marked as handled. They aren't told.":"¿Desactivar {name}? Nadie podrá ver su jardín, su perfil ni sus comentarios, ni encontrarle ni añadirle, hasta que la vuelvas a activar. Sus denuncias abiertas se marcan como resueltas. No se le avisa.",
"Marked as handled":"Marcada como resuelta", "{name} switched off":"{name}: cuenta desactivada", "{name} switched back on":"{name}: cuenta activada de nuevo",

/* ---- Messages from Alvor's server (functions and database) ---- */
"Please sign in.":"Inicia sesión.", "Add a photo first.":"Añade antes una foto.", "Alvor isn't set up correctly yet (database).":"Alvor aún no está bien configurado (base de datos).",
"Couldn't create the account. Try again.":"No se ha podido crear la cuenta. Vuelve a intentarlo.", "Couldn't reach the identification service.":"No se ha podido conectar con el servicio de identificación.",
"Couldn't remove your photos. Nothing was deleted; try again in a minute.":"No se han podido quitar tus fotos. No se ha borrado nada; vuelve a intentarlo en un minuto.",
"Plant identification isn't set up yet (PLANTNET_KEY is missing in Supabase).":"La identificación de plantas aún no está configurada (falta PLANTNET_KEY en Supabase).",
"That @username is already taken.":"Ese @usuario ya está cogido.", "That email doesn't look right.":"Ese correo no parece correcto.",
"That invite code has just been used. Ask for a new one.":"Ese código de invitación se acaba de usar. Pide uno nuevo.", "That invite code isn't valid. Ask for a new one.":"Ese código de invitación no es válido. Pide uno nuevo.",
"That password isn't right.":"Esa contraseña no es correcta.", "The Pl@ntNet key isn't accepted. Check PLANTNET_KEY in Supabase.":"La clave de Pl@ntNet no se acepta. Revisa PLANTNET_KEY en Supabase.",
"The identification service is busy for today. Type the name yourself for now.":"El servicio de identificación está saturado por hoy. De momento, escribe tú el nombre.",
"The password needs at least 8 characters.":"La contraseña necesita al menos 8 caracteres.",
"This is the owner's account, which runs Alvor's invitations and reports. It can only be removed from the Supabase dashboard.":"Esta es la cuenta del dueño, que gestiona las invitaciones y denuncias de Alvor. Solo se puede borrar desde el panel de Supabase.",
"This link doesn't work any more. Ask your friend for a new one.":"Este enlace ya no funciona. Pide uno nuevo a tu amigo.", "To create the first account, use your APP_KEY as the invite code.":"Para crear la primera cuenta, usa tu APP_KEY como código de invitación.",
"Use 3 to 24 letters, numbers, dots or dashes for your @username, with no spaces.":"Usa de 3 a 24 letras, números, puntos o guiones para tu @usuario, sin espacios.",
"You need an invite code or a friend's link to join.":"Para unirte necesitas un código de invitación o el enlace de un amigo.",
"You've used today's identifications. Try again tomorrow, or type the name yourself.":"Ya has usado las identificaciones de hoy. Vuelve a intentarlo mañana, o escribe tú el nombre.",
"Your friend has invited as many people as Alvor allows this month. Try again next month.":"Tu amigo ya ha invitado a todas las personas que Alvor permite este mes. Vuelve a intentarlo el mes que viene.",
"Your photos were removed, but the account couldn't be deleted. Try again in a minute.":"Tus fotos se han quitado, pero no se ha podido borrar la cuenta. Vuelve a intentarlo en un minuto.",
"There's already an account with that email. Sign in instead.":"Ya hay una cuenta con ese correo. Inicia sesión.",
"Only the owner of Alvor can create invite codes.":"Solo el dueño de Alvor puede crear códigos de invitación.", "Only the owner of Alvor can do that.":"Solo el dueño de Alvor puede hacer eso.",
"Only the owner of Alvor can see reports.":"Solo el dueño de Alvor puede ver las denuncias.", "Only the owner of Alvor can see this.":"Solo el dueño de Alvor puede ver esto.",
"That can't be reported.":"Eso no se puede denunciar.", "That person can't be added.":"No se puede añadir a esa persona.", "That request is no longer there.":"Esa solicitud ya no existe.",
"That's a lot of reactions for one hour. Try again a little later.":"Son muchas reacciones en una hora. Vuelve a intentarlo un poco más tarde.", "That's you.":"Eres tú.",
"That's your own link.":"Es tu propio enlace.", "That's yours.":"Es tuyo.", "This link doesn't work any more. Ask for a new one.":"Este enlace ya no funciona. Pide uno nuevo.",
"You can't switch off your own account.":"No puedes desactivar tu propia cuenta.", "You've sent a lot of reports today. Try again tomorrow.":"Hoy has mandado muchas denuncias. Vuelve a intentarlo mañana.",
"You've written a lot of comments in the last hour. Try again a little later.":"Has escrito muchos comentarios en la última hora. Vuelve a intentarlo un poco más tarde.",
"Couldn't create an invite. Try again.":"No se ha podido crear una invitación. Vuelve a intentarlo.", "Couldn't delete the account. Try again.":"No se ha podido borrar la cuenta. Vuelve a intentarlo.",
/* Care engine (Phase B) */
"No need":"No hace falta", "Probably not yet":"Probablemente aún no", "Consider watering":"Plantéate regarla", "Likely needs water":"Seguramente necesita agua", "Needs attention":"Necesita atención", "Not sure yet":"Aún no se sabe",
"Protect the crown of {n} plant:":"Protege la corona de {n} planta:", "Protect the crown of {n} plants:":"Protege la corona de {n} plantas:",
"Mulch the roots of {n} plant:":"Acolcha las raíces de {n} planta:", "Mulch the roots of {n} plants:":"Acolcha las raíces de {n} plantas:",
"Cover the new growth of {n} plant:":"Cubre los brotes nuevos de {n} planta:", "Cover the new growth of {n} plants:":"Cubre los brotes nuevos de {n} plantas:",
"Frost plan":"Plan para la helada", "Nothing to protect":"Nada que proteger",
"{n} plant likely needs water":"{n} planta seguramente necesita agua", "{n} plants likely need water":"{n} plantas seguramente necesitan agua",
"Not sure about these":"No sabemos de estas", "Already wet":"Aún húmeda", "Looks fine":"Se ve bien", "What did you find?":"¿Qué has visto?",
"checked {n}d ago":"revisada hace {n} d",
"Got it. Alvor will expect {name} to dry more slowly.":"Entendido. Alvor contará con que {name} tarde más en secarse.",
"Got it. Alvor will look at {name} again in a few days.":"Entendido. Alvor volverá a mirar {name} dentro de unos días.",
"Alvor will ask again tomorrow.":"Alvor volverá a preguntar mañana.",
"Against a wall":"Contra una pared", "Under a tree":"Bajo un árbol", "Windy spot":"Sitio con viento", "Hot afternoon sun":"Sol fuerte de tarde",
"An estimate from the weather, the spot and what you've told Alvor. It can't see the soil, so trust your finger.":"Es una estimación a partir del tiempo, el sitio y lo que le has dicho a Alvor. No ve la tierra: fíate de tu dedo.",
"The notify function on Supabase runs older care rules than this app. Deploy notify again so notifications and the app agree.":"La función notify de Supabase usa reglas de cuidado más antiguas que la app. Vuelve a desplegar notify para que los avisos y la app coincidan.",
"About this spot":"Sobre este sitio", "Only what changes Alvor's advice on frost, rain, drying and wind. Leave them off if you're not sure.":"Solo lo que cambia los consejos de Alvor sobre heladas, lluvia, secado y viento. Déjalos sin marcar si no estás seguro.",
"Water now":"Riego ahora", "{n} at risk from the cold":"{n} en riesgo por el frío",
/* Plant knowledge (plant-kb.js) */
"About this plant":"Sobre esta planta", "typical for {s}":"típico de {s}", "typical for the genus {s}":"típico del género {s}", "from its genus, {s}":"de su género, {s}",
"rough guess: its species take {lo} to {hi}":"estimación aproximada: sus especies aguantan de {lo} a {hi}",
"It's a rough guess: its species take {lo} to {hi}.":"Es una estimación aproximada: sus especies aguantan de {lo} a {hi}.",
"for plants that like it dry":"para plantas de poco riego", "for plants that like it moist":"para plantas de mucho riego", "for most plants":"para la mayoría de las plantas",
"for the genus {s}":"para el género {s}", "for {s}":"para {s}",
"Alvor doesn't know this plant yet. What you set here is used as it is.":"Alvor aún no conoce esta planta. Lo que pongas aquí se usa tal cual.",
"{t} is Alvor's value, {from}.":"{t} es el valor de Alvor, {from}.", "Lowest temperature: your own. Alvor says {t}, {from}.":"Temperatura mínima: la tuya. Alvor dice {t}, {from}.",
"Use Alvor's":"Usar el de Alvor",
"Watering: Alvor's suggestion {from}. Your answers to its watering advice still adjust it.":"Riego: la sugerencia de Alvor {from}. Tus respuestas a sus consejos de riego lo siguen ajustando.",
"Watering: your own. Alvor suggests every {s} days in summer and {w} in winter, {from}.":"Riego: el tuyo. Alvor sugiere cada {s} días en verano y {w} en invierno, {from}.",
"Takes about {t}":"Aguanta unos {t}", "rough guess":"estimación aproximada", "Roots survive to about {t} under a thick mulch":"Las raíces aguantan unos {t} bajo un buen acolchado",
"Protect the growing point in hard frost":"Protege el punto de crecimiento en heladas fuertes", "New growth is damaged below {t} in spring":"Los brotes nuevos se dañan por debajo de {t} en primavera",
"Wet cold harms it more than dry cold":"El frío húmedo le hace más daño que el frío seco", "Big leaves tear in strong wind":"Las hojas grandes se rompen con viento fuerte",
"Likes to dry out between waterings":"Le gusta secarse entre riegos", "Likes the soil kept moist":"Le gusta la tierra siempre húmeda",
"From Alvor's plant knowledge. What you set for your plant comes first.":"Del conocimiento de plantas de Alvor. Lo que pongas en tu planta va primero."
};
