/* Alvor · how much cold each plant takes.
   Lowest temperature (°C) before the plant is damaged, for an established plant in the ground,
   in a dry, sheltered spot. Pots are treated as 1 °C more tender by the alert rules.
   Plants that die back in winter and regrow (hostas, ferns, many perennials) are given the cold
   their roots take, so they don't raise warnings for frost that only blackens the leaves.
   These are typical values from nursery and hardiness references: young plants, wet winters
   and long cold spells all make a plant more tender. Adjust any plant in its edit screen.

   Key: "Genus" for the whole genus, "Genus species" for one species (wins over the genus).
   Value: a number, or [°C, through the year, note].
   Through the year: o = outside all year, m = outside in summer and inside in winter,
   g = greenhouse in winter, i = inside all year. Left out, it follows the temperature. */
window.HARDINESS = {
"Abelia":-15,
"Abies":-30,
"Abutilon":[0,"m"], "Abutilon megapotamicum":-7,
"Acacia":-5, "Acacia dealbata":[-8,"o","Young plants are more tender; flowers are lost below about −5 °C."], "Acacia baileyana":-6,
"Acanthus":-15,
"Acca":-12, "Acca sellowiana":-12,
"Acer":-25, "Acer palmatum":-20, "Acer negundo":-30,
"Achillea":-30,
"Aconitum":-30,
"Acorus":-25,
"Actinidia":-15, "Actinidia deliciosa":[-12,"o","Spring growth is killed by late frost even when the plant is fine."],
"Adiantum":-15, "Adiantum raddianum":[7,"i"],
"Aechmea":[10,"i"],
"Aeonium":[3,"m"], "Aeonium arboreum":2, "Aeonium haworthii":0,
"Aeschynanthus":[13,"i"],
"Aesculus":-30,
"Agapanthus":-8, "Agapanthus africanus":[-3,"m","Evergreen kinds are tender; deciduous kinds take much more cold."], "Agapanthus praecox":-5,
"Agave":-5, "Agave americana":[-8,"o","Wet cold kills more than dry cold. Keep rain off it in winter."], "Agave attenuata":[2,"m"], "Agave parryi":-18, "Agave victoriae-reginae":-8, "Agave montana":-15, "Agave salmiana":-8,
"Aglaonema":[13,"i"],
"Ajuga":-30,
"Akebia":-20,
"Albizia":-15,
"Alcea":-30,
"Alchemilla":-30,
"Allium":-25, "Allium schoenoprasum":-30, "Allium sativum":-20, "Allium cepa":-10,
"Alocasia":[10,"m"], "Alocasia amazonica":[15,"i"], "Alocasia zebrina":[15,"i"], "Alocasia macrorrhizos":[5,"m"], "Alocasia odora":[0,"m","Roots survive a few degrees of frost under thick mulch; the leaves don't."], "Alocasia wentii":[-3,"m","One of the hardiest: the roots can survive about −8 °C under thick mulch."],
"Aloe":[5,"m"], "Aloe vera":[5,"m"], "Aloe arborescens":[-2,"m"], "Aloe striatula":[-10,"o","Keep it dry in winter."], "Aloe polyphylla":[-8,"o","Needs very sharp drainage; wet winters kill it."],
"Aloysia":[-6,"o","The top dies back in hard frost and usually regrows from the base."],
"Alpinia":[5,"m"],
"Alstroemeria":-10,
"Amaryllis":-5, "Amaryllis belladonna":-7,
"Amorphophallus":[10,"m"], "Amorphophallus konjac":[-8,"o","Tubers survive in dry, well-mulched ground."],
"Anemone":-25, "Anemone coronaria":-10,
"Annona":[-2,"g"],
"Anethum":-5,
"Anthurium":[15,"i"],
"Antirrhinum":-10,
"Aquilegia":-30,
"Araucaria":-15, "Araucaria araucana":-20, "Araucaria heterophylla":[3,"m"],
"Arbutus":-15,
"Archontophoenix":[0,"m"],
"Argyranthemum":[-2,"m"],
"Arisaema":-15,
"Armeria":-30,
"Artemisia":-25, "Artemisia dracunculus":-20,
"Arum":-15,
"Aruncus":-30,
"Arundo":-15,
"Asimina":-25,
"Asparagus":-25, "Asparagus setaceus":[2,"m"], "Asparagus densiflorus":[0,"m"],
"Aspidistra":-10,
"Asplenium":-15, "Asplenium nidus":[13,"i"], "Asplenium scolopendrium":-25,
"Aster":-30,
"Astilbe":-30,
"Aucuba":-18,
"Azalea":-15,
"Bambusa":-5, "Bambusa multiplex":-9,
"Beaucarnea":[0,"m"],
"Begonia":[10,"m"], "Begonia rex":[12,"i"], "Begonia maculata":[12,"i"], "Begonia grandis":[-15,"o","Hardy begonia: dies back in winter and returns late in spring."], "Begonia semperflorens":[3,"m"], "Begonia luxurians":[5,"m"],
"Berberis":-25, "Berberis darwinii":-15,
"Bergenia":-30,
"Beschorneria":-8,
"Beta":-5,
"Betula":-35,
"Blechnum":-10, "Blechnum spicant":-20, "Blechnum chilense":-12,
"Bougainvillea":[3,"g"], "Bougainvillea glabra":[0,"g"],
"Brachychiton":-6,
"Brahea":-8, "Brahea armata":-10, "Brahea edulis":-4,
"Brassica":-10,
"Brugmansia":[3,"m"], "Brugmansia sanguinea":[0,"m"],
"Brunnera":-30,
"Buddleja":-20,
"Butia":-10,
"Buxus":-20,
"Caladium":[15,"i"],
"Calathea":[15,"i"],
"Calendula":-5,
"Callistemon":-8, "Callistemon viminalis":-5,
"Calluna":-25,
"Caltha":-30,
"Camellia":-15, "Camellia sasanqua":-12, "Camellia sinensis":-12,
"Campanula":-30,
"Campsis":-20,
"Canna":[0,"m","Cut back after frost blackens the leaves; lift the rhizomes or mulch deeply."],
"Capsicum":[5,"m"], "Capsicum chinense":[8,"m"],
"Carex":-20, "Carex buchananii":-15,
"Carica":[10,"i"],
"Carpinus":-30,
"Castanea":-25,
"Catalpa":-25,
"Ceanothus":-10,
"Cedrus":-20, "Cedrus deodara":-18, "Cedrus libani":-25,
"Centaurea":-20, "Centaurea cyanus":-15,
"Ceratostigma":-15,
"Cercis":-20, "Cercis siliquastrum":-15, "Cercis canadensis":-25,
"Cereus":[-2,"m"],
"Ceropegia":[7,"i"],
"Cestrum":-5, "Cestrum nocturnum":[-3,"m"],
"Chaenomeles":-25,
"Chamaedorea":[10,"i"], "Chamaedorea radicalis":[-4,"m"],
"Chamaerops":-10,
"Chlorophytum":[5,"i"],
"Choisya":-12,
"Chrysanthemum":-15,
"Chusquea":-12,
"Cissus":[7,"i"],
"Cistus":-10, "Cistus ladanifer":-8, "Cistus x purpureus":-8,
"Citrus":[-2,"g","Flowers and fruit are damaged before the tree is."], "Citrus limon":[-2,"g"], "Citrus sinensis":[-3,"g"], "Citrus reticulata":[-4,"g"], "Citrus aurantium":[-6,"g"], "Citrus x meyeri":[-3,"g"], "Citrus japonica":[-7,"g"], "Citrus hystrix":[2,"g"], "Citrus aurantiifolia":[2,"g"],
"Clematis":-25, "Clematis armandii":-12, "Clematis montana":-20,
"Clerodendrum":-15,
"Clivia":[2,"m"],
"Codiaeum":[13,"i"],
"Coffea":[10,"i"],
"Colocasia":[2,"m","Leaves collapse near 0 °C. Bring pots in, or cut back and mulch tubers heavily in the ground."], "Colocasia fallax":[5,"m"], "Colocasia gigantea":[5,"m"],
"Columnea":[13,"i"],
"Convallaria":-30,
"Convolvulus":-5, "Convolvulus cneorum":-8,
"Coprosma":-4,
"Cordyline":-6, "Cordyline australis":[-6,"o","Tie the leaves up around the growing point in a hard frost."], "Cordyline fruticosa":[10,"i"],
"Coreopsis":-25,
"Coriandrum":-5,
"Cornus":-25, "Cornus alba":-35,
"Cortaderia":-15,
"Corylus":-30,
"Cosmos":0, "Cosmos atrosanguineus":[-5,"m"],
"Cotinus":-25,
"Cotoneaster":-25,
"Crassula":[2,"m"], "Crassula arborescens":[0,"m"],
"Crinum":-12,
"Crocosmia":-15,
"Crocus":-30,
"Ctenanthe":[13,"i"],
"Cucumis":5,
"Cucurbita":3,
"Cupressus":-15, "Cupressus macrocarpa":-12,
"Curcuma":[10,"m"],
"Curio":[5,"i"],
"Cyathea":[0,"g"], "Cyathea cooperi":[-2,"g"], "Cyathea dealbata":[-3,"g"], "Cyathea medullaris":[-2,"g"],
"Cycas":[-6,"g","Keep fairly dry in winter and protect the crown from wet and frost."],
"Cyclamen":-15, "Cyclamen persicum":[5,"i"], "Cyclamen hederifolium":-20, "Cyclamen coum":-20,
"Cydonia":-25,
"Cylindropuntia":-15,
"Cymbidium":[3,"m"],
"Cymbopogon":[5,"m"],
"Cynara":-12,
"Cyperus":[0,"m"], "Cyperus papyrus":[5,"m"],
"Cyrtomium":-15,
"Dahlia":[0,"m","The top dies at the first frost. Lift the tubers, or mulch them deeply in dry ground."],
"Daphne":-15, "Daphne odora":-10,
"Darmera":-25,
"Dasylirion":-12, "Dasylirion longissimum":-10,
"Datura":[0,"m"],
"Daucus":-10,
"Davallia":[10,"i"],
"Delosperma":-20,
"Delphinium":-30,
"Dendrobium":[10,"i"], "Dendrobium nobile":[5,"m"],
"Deutzia":-25,
"Dianthus":-20, "Dianthus caryophyllus":-10,
"Dicentra":-30,
"Dicksonia":[-5,"o","Water the trunk, not just the soil. Stuff the crown with straw or cover it with fleece in hard frost."], "Dicksonia squarrosa":[-3,"g"], "Dicksonia fibrosa":-7,
"Dieffenbachia":[15,"i"],
"Digitalis":-25,
"Diospyros":-15,
"Dionaea":-8,
"Dracaena":[12,"i"], "Dracaena draco":[0,"m"], "Dracaena trifasciata":[10,"i"], "Dracaena sanderiana":[15,"i"],
"Drosera":[0,"m"],
"Dryopteris":-30, "Dryopteris erythrosora":-25,
"Dypsis":[5,"i"], "Dypsis lutescens":[10,"i"], "Dypsis decaryi":[0,"m"],
"Echeveria":[2,"m"], "Echeveria elegans":[0,"m"], "Echeveria agavoides":[0,"m"],
"Echinacea":-30,
"Echinocactus":[5,"m"],
"Echinops":-30,
"Echinopsis":[0,"m"],
"Echium":[-3,"g"], "Echium wildpretii":[-5,"g"],
"Edgeworthia":-12,
"Elaeagnus":-20,
"Ensete":[1,"m","Tender. Bring inside or lift before the first frost."], "Ensete glaucum":[3,"m"],
"Epimedium":-25,
"Epipremnum":[12,"i"],
"Equisetum":-30,
"Erica":-20, "Erica carnea":-30, "Erica arborea":-12,
"Erigeron":-15,
"Eriobotrya":[-12,"o","The tree is hardy, but winter flowers and young fruit are lost below about −3 °C."],
"Eryngium":-20, "Eryngium agavifolium":-12,
"Erysimum":-15,
"Escallonia":-10,
"Eucalyptus":-10, "Eucalyptus gunnii":-15, "Eucalyptus globulus":-7,
"Eucomis":-10,
"Euonymus":-20, "Euonymus japonicus":-15, "Euonymus fortunei":-25,
"Euphorbia":[5,"m"], "Euphorbia pulcherrima":[10,"i"], "Euphorbia milii":[8,"i"], "Euphorbia characias":-15, "Euphorbia trigona":[10,"i"], "Euphorbia tirucalli":[5,"m"], "Euphorbia mellifera":-7,
"Farfugium":-12,
"Fargesia":-25,
"Fascicularia":-10,
"Fatshedera":-12,
"Fatsia":[-12,"o","Very hardy. Keep pots from freezing solid."],
"Feijoa":-12,
"Festuca":-30,
"Ficus":[10,"i"], "Ficus carica":[-12,"o","Young shoots die back in hard frost; established trees regrow."], "Ficus elastica":[5,"i"], "Ficus pumila":[-5,"m"], "Ficus microcarpa":[5,"i"],
"Fittonia":[15,"i"],
"Forsythia":-25,
"Fortunella":[-7,"g"],
"Fragaria":-20,
"Freesia":[0,"m"],
"Fuchsia":[0,"m"], "Fuchsia magellanica":-15,
"Gaillardia":-25,
"Galanthus":-30,
"Gardenia":[5,"i"],
"Gasteria":[3,"m"],
"Gaura":-15,
"Gazania":[-3,"m"],
"Geranium":-25, "Geranium maderense":[-2,"m"],
"Gerbera":[0,"m"],
"Ginkgo":-30,
"Gladiolus":-5, "Gladiolus communis":-15,
"Goeppertia":[15,"i"],
"Grevillea":-8, "Grevillea rosmarinifolia":-12,
"Gunnera":[-10,"o","Leaves die at the first frost. Fold them over the crown and add straw before winter."], "Gunnera tinctoria":-10,
"Guzmania":[12,"i"],
"Gymnocalycium":[0,"m"],
"Gynura":[12,"i"],
"Hakonechloa":-25,
"Hamamelis":-25,
"Haworthia":[5,"i"],
"Haworthiopsis":[5,"i"],
"Hebe":-10, "Hebe pinguifolia":-15, "Hebe x franciscana":-7,
"Hedera":-20,
"Hedychium":[-5,"o","Dies back in winter; mulch the rhizomes."], "Hedychium gardnerianum":-3, "Hedychium coccineum":-8, "Hedychium densiflorum":-12, "Hedychium coronarium":-3, "Hedychium forrestii":-10,
"Helianthus":0,
"Helichrysum":-15, "Helichrysum petiolare":[-2,"m"],
"Heliconia":[12,"i"],
"Helleborus":-25, "Helleborus argutifolius":-15,
"Hemerocallis":-30,
"Hesperaloe":-18,
"Hesperoyucca":-10,
"Heuchera":-30,
"Hibiscus":-20, "Hibiscus rosa-sinensis":[7,"m"], "Hibiscus syriacus":-25, "Hibiscus moscheutos":-25,
"Hippeastrum":[5,"i"],
"Hosta":-35,
"Howea":[5,"i"],
"Hoya":[10,"i"],
"Hyacinthus":-25,
"Hydrangea":-20, "Hydrangea macrophylla":[-15,"o","Hardy, but late frost kills the flower buds."], "Hydrangea paniculata":-30, "Hydrangea quercifolia":-25, "Hydrangea petiolaris":-30, "Hydrangea arborescens":-30, "Hydrangea aspera":-15,
"Hypericum":-20,
"Hypoestes":[10,"i"],
"Iberis":-25,
"Ilex":-20,
"Impatiens":[5,"m"], "Impatiens tinctoria":-10,
"Iris":-25,
"Jasminum":-10, "Jasminum officinale":-12, "Jasminum polyanthum":[-3,"m"], "Jasminum nudiflorum":-20, "Jasminum sambac":[7,"i"],
"Jubaea":-12,
"Juglans":-25,
"Juncus":-25,
"Juniperus":-30,
"Kalanchoe":[7,"i"], "Kalanchoe thyrsiflora":[5,"i"],
"Kalopanax":-25,
"Kniphofia":-15, "Kniphofia caulescens":-12,
"Lactuca":-5,
"Lagerstroemia":-15,
"Lantana":[0,"m"],
"Laurus":-12,
"Lavandula":-15, "Lavandula angustifolia":-20, "Lavandula stoechas":-8, "Lavandula x intermedia":-18, "Lavandula dentata":[-5,"m"],
"Leucadendron":[-3,"g"],
"Leucanthemum":-30,
"Levisticum":-30,
"Ligularia":-30,
"Ligustrum":-15,
"Lilium":-25, "Lilium candidum":-20,
"Liquidambar":-25,
"Liriodendron":-30,
"Liriope":-20,
"Lithops":[5,"i"],
"Livistona":[-4,"m"], "Livistona chinensis":[-5,"o"], "Livistona australis":-6,
"Lobelia":-20, "Lobelia erinus":0, "Lobelia tupa":-8,
"Lonicera":-25, "Lonicera nitida":-20, "Lonicera japonica":-20,
"Lupinus":-30,
"Lysichiton":-25,
"Magnolia":-20, "Magnolia grandiflora":-15, "Magnolia stellata":-25, "Magnolia x soulangeana":-25, "Magnolia liliiflora":-25, "Magnolia kobus":-25,
"Mahonia":-15, "Mahonia aquifolium":-25, "Mahonia eurybracteata":-12,
"Malus":-30,
"Malva":-20,
"Mammillaria":[3,"m"],
"Mandevilla":[7,"m"], "Mandevilla laxa":-5,
"Mangifera":[5,"g"],
"Maranta":[15,"i"],
"Matteuccia":-35,
"Melianthus":[-5,"o","The top dies back around −5 °C; mulched roots survive about −10 °C and regrow."],
"Melissa":-20,
"Mentha":-25,
"Mespilus":-20,
"Metasequoia":-30,
"Miscanthus":-25,
"Monstera":[12,"i"], "Monstera adansonii":[13,"i"], "Monstera obliqua":[15,"i"],
"Morus":-25,
"Musa":[5,"m"], "Musa basjoo":[-3,"o","The trunk is damaged around −3 °C; the roots survive to about −10 °C under thick mulch. Wrap the trunk or cut it back and mulch before hard frost."], "Musa sikkimensis":[-2,"o","Like Musa basjoo: wrap or cut back the trunk and mulch the roots."], "Musa velutina":[0,"m"], "Musa itinerans":[-1,"m"], "Musa balbisiana":[2,"m"], "Musa acuminata":[5,"m"], "Musa x paradisiaca":[5,"m"],
"Musella":[-5,"o","Roots survive about −10 °C under thick mulch."],
"Muscari":-30,
"Myosotis":-25,
"Myrtus":-10,
"Nandina":-15,
"Narcissus":-30, "Narcissus tazetta":-10,
"Nelumbo":[-10,"o","Survives if the tubers sit below the ice."],
"Nepenthes":[12,"i"],
"Nepeta":-30,
"Nephrolepis":[10,"i"],
"Nerium":[-5,"g"],
"Nicotiana":0, "Nicotiana sylvestris":-5,
"Nolina":-12,
"Nymphaea":-30,
"Ocimum":[8,"m"],
"Olea":-8,
"Opuntia":-5, "Opuntia ficus-indica":-5, "Opuntia microdasys":[0,"m"], "Opuntia humifusa":-25,
"Origanum":-20, "Origanum majorana":-5,
"Osmanthus":-15, "Osmanthus fragrans":-8, "Osmanthus x burkwoodii":-20,
"Osmunda":-30,
"Osteospermum":-5,
"Oxalis":-10, "Oxalis triangularis":[0,"m"],
"Pachira":[10,"i"],
"Pachysandra":-30,
"Paeonia":-30,
"Papaver":-30,
"Parthenocissus":-30,
"Passiflora":[0,"g"], "Passiflora caerulea":[-10,"o","The top can die in hard frost and regrows from the roots."], "Passiflora edulis":[0,"g"],
"Paulownia":-20,
"Pelargonium":[0,"m"], "Pelargonium sidoides":[-3,"m"],
"Pennisetum":-20, "Pennisetum setaceum":[0,"m"],
"Penstemon":-15,
"Peperomia":[10,"i"],
"Perovskia":-25,
"Persea":[-3,"g"],
"Persicaria":-30,
"Petasites":-25,
"Petroselinum":-10,
"Petunia":0,
"Phalaenopsis":[15,"i"],
"Phaseolus":5,
"Philadelphus":-30,
"Philodendron":[12,"i"], "Philodendron bipinnatifidum":[0,"m"],
"Phlomis":-15, "Phlomis russeliana":-25,
"Phlox":-30,
"Phoenix":-5, "Phoenix canariensis":-7, "Phoenix dactylifera":-8, "Phoenix roebelenii":[2,"m"],
"Phormium":[-8,"o","Variegated forms are more tender."], "Phormium cookianum":-8,
"Photinia":-18,
"Phyllostachys":-20, "Phyllostachys edulis":-15, "Phyllostachys bissetii":-25, "Phyllostachys vivax":-25,
"Picea":-40,
"Pieris":-20,
"Pilea":[10,"i"], "Pilea peperomioides":[5,"i"],
"Pinus":-30, "Pinus pinea":-15, "Pinus thunbergii":-25,
"Pisum":-5,
"Pittosporum":-10,
"Platanus":-25,
"Platycerium":[10,"i"],
"Plectranthus":[5,"m"],
"Pleioblastus":-20,
"Plumbago":[-2,"m"],
"Podocarpus":-10, "Podocarpus macrophyllus":-12,
"Polygonatum":-30,
"Polypodium":-15,
"Polystichum":-25, "Polystichum polyblepharum":-20,
"Pontederia":-20,
"Primula":-25, "Primula obconica":[5,"i"],
"Protea":[-3,"g"],
"Prunus":-25, "Prunus persica":[-20,"o","Blossom is killed by frost below about −2 °C."], "Prunus armeniaca":[-20,"o","Blossom is killed by frost below about −2 °C."], "Prunus dulcis":[-15,"o","Blossom is killed by frost below about −2 °C."], "Prunus laurocerasus":-20, "Prunus lusitanica":-15, "Prunus avium":-30, "Prunus domestica":-30,
"Pseudopanax":-7, "Pseudopanax lessonii":-5,
"Psidium":[0,"g"],
"Pulmonaria":-30,
"Punica":-12,
"Puya":-8,
"Pyracantha":-20,
"Pyrus":-30, "Pyrus calleryana":-25,
"Quercus":-30, "Quercus ilex":-15, "Quercus suber":-10, "Quercus rubra":-35,
"Ranunculus":-25, "Ranunculus asiaticus":[-5,"m"],
"Ravenala":[10,"i"],
"Rhaphidophora":[13,"i"],
"Rhapidophyllum":-18,
"Rhapis":[-4,"m"],
"Rheum":-30, "Rheum palmatum":-25,
"Rhipsalis":[7,"i"],
"Rhododendron":-20, "Rhododendron simsii":[0,"m"], "Rhododendron yakushimanum":-25, "Rhododendron luteum":-25,
"Rhus":-30,
"Ribes":-30, "Ribes sanguineum":-20,
"Ricinus":2,
"Rodgersia":-25,
"Rosa":-20, "Rosa banksiae":-10, "Rosa rugosa":-35,
"Rosmarinus":-10,
"Rubus":-25,
"Rudbeckia":-30, "Rudbeckia hirta":-20,
"Ruscus":-15,
"Sabal":-12, "Sabal minor":-15, "Sabal palmetto":-10,
"Sagittaria":-20,
"Saintpaulia":[15,"i"],
"Salix":-30, "Salix babylonica":-25,
"Salvia":-5, "Salvia officinalis":-15, "Salvia nemorosa":-30, "Salvia rosmarinus":-10, "Salvia elegans":[-3,"m"], "Salvia microphylla":-10, "Salvia guaranitica":-8,
"Sambucus":-30,
"Sansevieria":[10,"i"],
"Santolina":-15,
"Sarcococca":-20,
"Sasa":-25,
"Saxifraga":-20, "Saxifraga stolonifera":-10,
"Schefflera":[5,"i"], "Schefflera actinophylla":[10,"i"], "Schefflera taiwaniana":-10, "Schefflera delavayi":-10, "Schefflera rhododendrifolia":-12,
"Schlumbergera":[5,"i"],
"Scilla":-30,
"Scindapsus":[13,"i"],
"Sedum":-25, "Sedum spectabile":-30, "Sedum acre":-30, "Sedum morganianum":[5,"i"], "Sedum rubrotinctum":[0,"m"],
"Sempervivum":-30,
"Senecio":[0,"m"], "Senecio rowleyanus":[5,"i"], "Senecio cineraria":-5,
"Skimmia":-20,
"Soleirolia":-10,
"Solanum":[2,"m"], "Solanum lycopersicum":5, "Solanum melongena":8, "Solanum tuberosum":0, "Solanum laxum":-8, "Solanum crispum":-10, "Solanum rantonnetii":[0,"m"],
"Solenostemon":[8,"m"],
"Sorbus":-35,
"Spathiphyllum":[12,"i"],
"Spinacia":-10,
"Spiraea":-30,
"Stachys":-30,
"Stevia":[0,"m"],
"Stipa":-20, "Stipa tenuissima":-15,
"Strelitzia":[3,"m"], "Strelitzia nicolai":[2,"m"],
"Streptocarpus":[10,"i"],
"Stromanthe":[13,"i"],
"Syngonium":[13,"i"],
"Syringa":-30,
"Tagetes":2,
"Taxus":-25,
"Tetrapanax":[-8,"o","Top can die back in hard frost and regrows from the roots. Mulch the base."],
"Thalia":-10,
"Thuja":-35,
"Thymus":-20, "Thymus citriodorus":-15,
"Tillandsia":[8,"i"], "Tillandsia usneoides":[0,"m"],
"Trachelospermum":-10, "Trachelospermum asiaticum":-12,
"Trachycarpus":[-15,"o","Very hardy palm. Keep water out of the crown in wet winters."], "Trachycarpus princeps":-12,
"Tradescantia":[3,"i"], "Tradescantia zebrina":[5,"i"], "Tradescantia pallida":[-3,"m"], "Tradescantia fluminensis":[0,"m"], "Tradescantia spathacea":[10,"i"],
"Trochodendron":-15,
"Tropaeolum":0,
"Tulipa":-30,
"Typha":-30,
"Vaccinium":-25,
"Verbena":-10, "Verbena officinalis":-20,
"Veronica":-30,
"Viburnum":-20, "Viburnum tinus":-12, "Viburnum opulus":-35, "Viburnum plicatum":-25, "Viburnum x bodnantense":-25, "Viburnum davidii":-15,
"Vinca":-20, "Vinca major":-15,
"Viola":-20, "Viola x wittrockiana":-15,
"Vitis":-20,
"Washingtonia":-5, "Washingtonia filifera":-8, "Washingtonia robusta":-5,
"Weigela":-30,
"Wisteria":-25,
"Woodwardia":-8, "Woodwardia unigemmata":-10,
"Xanthosoma":[10,"m"],
"Yucca":-10, "Yucca elephantipes":[2,"m"], "Yucca gloriosa":-15, "Yucca filamentosa":-25, "Yucca rostrata":-18, "Yucca aloifolia":-8,
"Zamioculcas":[12,"i"],
"Zantedeschia":-10,
"Zea":2,
"Zingiber":[5,"m"], "Zingiber mioga":-15,
"Zinnia":2
};
